ReplicaNumber: 3

containers:
  containerPort: 8080
  image: 'quay.io/eliav_nili/app-dev-lab'
  tag: 'chart_v1'

service:
  servicePort: 8080
probe:
  readiness:
    initialDelaySeconds: 1
    path: '/health/readiness'
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  liveness:
    path: '/health/liveliness'
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
volumeMounts:
  mountPath: '/tmp/html'