ReplicaNumber: 3

containers:
  containerPort: 8080
  image: 'quay.io/eliav_nili/app-dev-lab'
  tag: 'chart_v1'

service:
  servicePort: 8080
readinessProbe:
      initialDelaySeconds: 30
      path: '/health/readiness'