ReplicaNumber: 3

containers:
  containerPort: 8080
  image: 'quay.io/eliav_nili/app-dev-lab'
  tag: 'chart_v1'

service:
  servicePort: 8080
readinessProbe:
      failureThreshold: 2
      initialDelaySeconds: 30
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 30
 livenessProbe:
      failureThreshold: 4
      initialDelaySeconds: 30
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 30